green_nub_detector_node_v2:
  ros__parameters:
    image_topic: /camera/camera/color/image_raw
    camera_info_topic: /camera/camera/color/camera_info
    debug_image_topic: /aydin_v2/green_nubs/debug_image_v2
    aruco_dictionary_id: DICT_4X4_50
    aruco_marker_id: 1
    aruco_marker_size: 0.04
    aruco_axis_length: 0.02
    aruco_pose_topic: /aydin_v2/aruco_poses_v2
    camera_frame: camera_color_optical_frame
    depth_topic: /camera/camera/aligned_depth_to_color/image_raw
    target_frame: base_link
    live_nub_pose_topic: /aydin_v2/live_nubs_v2/poses
    live_nub_detection_topic: /aydin_v2/live_nubs_v2/detections
    snapshot_service_name: /take_nub_snapshot_v2
    green_h_min: 35
    green_h_max: 85
    green_s_min: 80
    green_s_max: 255
    green_v_min: 50
    green_v_max: 255
    green_min_area: 20.0
    green_max_area: 800.0
    green_min_circularity: 0.35
    green_blur_kernel_size: 3
    green_morph_kernel_size: 3
    enable_tuning_window: true
    tuning_config_path: green_detection_params_v2.json

nub_snapshot_node_v2:
  ros__parameters:
    live_nub_detection_topic: /aydin_v2/live_nubs_v2/detections
    debug_image_topic: /aydin_v2/green_nubs/debug_image_v2
    target_frame: base_link
    snapshot_duration: 3.0
    snapshot_expected_nubs: 11
    snapshot_cluster_radius: 0.025
    snapshot_min_samples: 5
    snapshot_pose_topic: /aydin_v2/nub_snapshot_v2/poses
    snapshot_point_topic: /aydin_v2/nub_snapshot_v2/points
    snapshot_frame_prefix: snapshot_nub_v2
    snapshot_service_name: /take_nub_snapshot_v2
    enable_snapshot_popup: true

nub_path_executor_node_v2:
  ros__parameters:
    snapshot_pose_topic: /aydin_v2/nub_snapshot_v2/poses
    path_topic: /aydin_v2/nub_path_v2/path
    execute_service_name: /plan_execute_nub_path_v2
    joint_states_topic: /joint_states
    cartesian_path_service_name: /compute_cartesian_path
    execute_trajectory_action_name: /execute_trajectory
    gripper_service_name: /toggle_gripper
    target_frame: base_link
    end_effector_frame: wrist_3_link
    move_group_name: ur_manipulator
    planning_link_name: wrist_3_link
    hover_z_offset: 0.10
    curve_samples_per_segment: 8
    cartesian_max_step: 0.01
    cartesian_jump_threshold: 0.0
    minimum_cartesian_fraction: 0.95
    max_joint_speed: 0.45
    min_waypoint_dt: 0.20
    client_timeout_sec: 10.0
    gripper_toggle_delay_sec: 0.5
    gripper_cycles_per_nub: 1
    post_segment_settle_sec: 0.2
    shutdown_after_execution: true
    avoid_collisions: true
    use_current_end_effector_orientation: true
    tool_orientation_x: 0.0
    tool_orientation_y: 1.0
    tool_orientation_z: 0.0
    tool_orientation_w: 0.0
